version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo dnf update -y
      - sudo dnf install nginx -y
  build:
    commands:
      - echo Build started on `date`
      - sudo cp index.html /usr/share/nginx/html/
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - '**/*'

